---
label: project
hide_body: false
is_partial: false
fields:
- type: text
  name: title
  label: Title
- name: sub_heading
  label: Sub Heading
  type: text
  hidden: false
  default: ''
- name: banner_image
  label: Banner Image
  type: file
  description: Dimensions work best at 1200 pixels by 400 pixels
  hidden: false
  default: ''
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- name: slug
  label: Slug
  type: text
  hidden: false
  default: ''
- type: tag_list
  name: malware
  label: malware
  hidden: false
- type: include
- type: select
  config:
    source:
      type: documents
pages:
- _projects/how-i-used-a-i.md
- _projects/git-basics.md
- _projects/web-deleopment.md
- _projects/machine-learning-with-a-webcam.md
- _projects/computer-vision-set-up-introduction.md
- _projects/how-to-set-up-jupyterhub.md
- _projects/backwardchaining.md
